import requests
import pandas as pd
from tqdm import tqdm

# Using Google Cloud API Key
API_KEY = 'SECRET'

# Initialising the scrapped lists including information about the stations names
# with their English, Cantonese names and the respective URL map links

kwun_tong_stations = [
    {"station_eng": "Whampoa", "station_canto": "黃埔", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/wha.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/wha.pdf"},
    {"station_eng": "Ho Man Tin", "station_canto": "何文田", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/hom.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/hom.pdf"},
    {"station_eng": "Yau Ma Tei", "station_canto": "油麻地", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/yat.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/yat.pdf"},
    {"station_eng": "Mong Kok", "station_canto": "旺角", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/mok.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/mok.pdf"},
    {"station_eng": "Prince Edward", "station_canto": "太子", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/pre.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/pre.pdf"},
    {"station_eng": "Shek Kip Mei", "station_canto": "石硤尾", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/skm.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/skm.pdf"},
    {"station_eng": "Kowloon Tong", "station_canto": "九龍塘", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/kot.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/kot.pdf"},
    {"station_eng": "Lok Fu", "station_canto": "樂富", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/lof.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/lof.pdf"},
    {"station_eng": "Wong Tai Sin", "station_canto": "黃大仙", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/wts.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/wts.pdf"},
    {"station_eng": "Diamond Hill", "station_canto": "鑽石山", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/dih.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/dih.pdf"},
    {"station_eng": "Choi Hung", "station_canto": "彩虹", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/chh.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/chh.pdf"},
    {"station_eng": "Kowloon Bay", "station_canto": "九龍灣", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/kob.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/kob.pdf"},
    {"station_eng": "Ngau Tau Kok", "station_canto": "牛頭角", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/ntk.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/ntk.pdf"},
    {"station_eng": "Kwun Tong", "station_canto": "觀塘", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/kwt.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/kwt.pdf"},
    {"station_eng": "Lam Tin", "station_canto": "藍田", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/lat.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/lat.pdf"},
    {"station_eng": "Yau Tong", "station_canto": "油塘", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/yat.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/yat.pdf"},
    {"station_eng": "Tiu Keng Leng", "station_canto": "調景嶺", "line": "Kwun Tong",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tik.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tik.pdf"}
]

tsuen_wan_stations = [
    {"station_eng": "Tsuen Wan", "station_canto": "荃灣", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tsw.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tsw.pdf"},
    {"station_eng": "Tai Wo Hau", "station_canto": "大窩口", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/twh.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/twh.pdf"},
    {"station_eng": "Kwai Hing", "station_canto": "葵興", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/kwh.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/kwh.pdf"},
    {"station_eng": "Kwai Fong", "station_canto": "葵芳", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/kwf.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/kwf.pdf"},
    {"station_eng": "Lai King", "station_canto": "荔景", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/lak.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/lak.pdf"},
    {"station_eng": "Mei Foo", "station_canto": "美孚", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/mef.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/mef.pdf"},
    {"station_eng": "Lai Chi Kok", "station_canto": "荔枝角", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/lck.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/lck.pdf"},
    {"station_eng": "Cheung Sha Wan", "station_canto": "長沙灣", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/csw.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/csw.pdf"},
    {"station_eng": "Sham Shui Po", "station_canto": "深水埗", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/ssp.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/ssp.pdf"},
    {"station_eng": "Prince Edward", "station_canto": "太子", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/pre.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/pre.pdf"},
    {"station_eng": "Mong Kok", "station_canto": "旺角", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/mok.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/mok.pdf"},
    {"station_eng": "Yau Ma Tei", "station_canto": "油麻地", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/yat.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/yat.pdf"},
    {"station_eng": "Jordan", "station_canto": "佐敦", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/jor.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/jor.pdf"},
    {"station_eng": "Tsim Sha Tsui", "station_canto": "尖沙咀", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tst.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tst.pdf"},
    {"station_eng": "Admiralty", "station_canto": "金鐘", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/adm.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/adm.pdf"},
    {"station_eng": "Central", "station_canto": "中環", "line": "Tsuen Wan",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/cen.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/cent.pdf"}
]

island_line_stations = [
    {"station_eng": "Kennedy Town", "station_canto": "堅尼地城", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/ket.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/ket.pdf"},
    {"station_eng": "HKU", "station_canto": "香港大學", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/hku.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/hku.pdf"},
    {"station_eng": "Sai Ying Pun", "station_canto": "西營盤", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/syp.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/syp.pdf"},
    {"station_eng": "Sheung Wan", "station_canto": "上環", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/shw.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/shw.pdf"},
    {"station_eng": "Central", "station_canto": "中環", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/cen.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/cen.pdf"},
    {"station_eng": "Admiralty", "station_canto": "金鐘", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/adm.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/adm.pdf"},
    {"station_eng": "Wan Chai", "station_canto": "灣仔", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/wac.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/wac.pdf"},
    {"station_eng": "Causeway Bay", "station_canto": "銅鑼灣", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/cab.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/cab.pdf"},
    {"station_eng": "Tin Hau", "station_canto": "天后", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tih.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tih.pdf"},
    {"station_eng": "Fortress Hill", "station_canto": "炮台山", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/foh.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/foh.pdf"},
    {"station_eng": "North Point", "station_canto": "北角", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/nop.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/nop.pdf"},
    {"station_eng": "Quarry Bay", "station_canto": "鰂魚涌", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/qub.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/qub.pdf"},
    {"station_eng": "Tai Koo", "station_canto": "太古", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tik.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tik.pdf"},
    {"station_eng": "Sai Wan Ho", "station_canto": "西灣河", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/swh.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/swh.pdf"},
    {"station_eng": "Shau Kei Wan", "station_canto": "筲箕灣", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/skw.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/skw.pdf"},
    {"station_eng": "Heng Fa Chuen", "station_canto": "杏花邨", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/hfc.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/hfc.pdf"},
    {"station_eng": "Chai Wan", "station_canto": "柴灣", "line": "Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/chw.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/chw.pdf"}
]

south_island_line_stations = [
    {"station_eng": "South Horizons", "station_canto": "海怡半島", "line": "South Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/soh.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/soh.pdf"},
    {"station_eng": "Lei Tung", "station_canto": "利東", "line": "South Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/let.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/let.pdf"},
    {"station_eng": "Wong Chuk Hang", "station_canto": "黃竹坑", "line": "South Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/wch.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/wch.pdf"},
    {"station_eng": "Ocean Park", "station_canto": "海洋公園", "line": "South Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/ocp.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/ocp.pdf"},
    {"station_eng": "Admiralty", "station_canto": "金鐘", "line": "South Island",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/adm.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/adm.pdf"}
]

tseung_kwan_o_line_stations = [
    {"station_eng": "North Point", "station_canto": "北角", "line": "Tseung Kwan O",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/nop.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/nop.pdf"},
    {"station_eng": "Quarry Bay", "station_canto": "鰂魚涌", "line": "Tseung Kwan O",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/qub.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/qub.pdf"},
    {"station_eng": "Yau Tong", "station_canto": "油塘", "line": "Tseung Kwan O",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/yat.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/yat.pdf"},
    {"station_eng": "Tiu Keng Leng", "station_canto": "調景嶺", "line": "Tseung Kwan O",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tik.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tik.pdf"},
    {"station_eng": "Tseung Kwan O", "station_canto": "將軍澳", "line": "Tseung Kwan O",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tko.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tko.pdf"},
    {"station_eng": "Hang Hau", "station_canto": "坑口", "line": "Tseung Kwan O",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/hah.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/hah.pdf"},
    {"station_eng": "Po Lam", "station_canto": "寶琳", "line": "Tseung Kwan O",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/poa.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/poa.pdf"},
    {"station_eng": "LOHAS Park", "station_canto": "康城", "line": "Tseung Kwan O",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/lhp.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/lhp.pdf"}
]

tung_chung_line_stations = [
    {"station_eng": "Hong Kong", "station_canto": "香港", "line": "Tung Chung",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/hok.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/hok.pdf"},
    {"station_eng": "Kowloon", "station_canto": "九龍", "line": "Tung Chung",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/kow.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/kow.pdf"},
    {"station_eng": "Olympic", "station_canto": "奧運", "line": "Tung Chung",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/oly.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/oly.pdf"},
    {"station_eng": "Nam Cheong", "station_canto": "南昌", "line": "Tung Chung",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/nac.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/nac.pdf"},
    {"station_eng": "Lai King", "station_canto": "荔景", "line": "Tung Chung",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/lak.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/lak.pdf"},
    {"station_eng": "Tsing Yi", "station_canto": "青衣", "line": "Tung Chung",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tsy.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tsy.pdf"},
    {"station_eng": "Sunny Bay", "station_canto": "欣澳", "line": "Tung Chung",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/sun.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/sun.pdf"},
    {"station_eng": "Tung Chung", "station_canto": "東涌", "line": "Tung Chung",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tuc.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tuc.pdf"}
]

disneyland_resort_line_stations = [
    {"station_eng": "Sunny Bay", "station_canto": "欣澳", "line": "Disneyland Resort",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/sun.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/sun.pdf"},
    {"station_eng": "Disneyland Resort", "station_canto": "迪士尼", "line": "Disneyland Resort",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/dis.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/dis.pdf"}
]

east_rail_line_stations = [
    {"station_eng": "Admiralty", "station_canto": "金鐘", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/adm.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/adm.pdf"},
    {"station_eng": "Exhibition Centre", "station_canto": "會展", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/exc.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/exc.pdf"},
    {"station_eng": "Hung Hom", "station_canto": "紅磡", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/huh.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/huh.pdf"},
    {"station_eng": "Mong Kok East", "station_canto": "旺角東", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/mkk.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/mkk.pdf"},
    {"station_eng": "Kowloon Tong", "station_canto": "九龍塘", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/kot.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/kot.pdf"},
    {"station_eng": "Tai Wai", "station_canto": "大圍", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/taw.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/taw.pdf"},
    {"station_eng": "Sha Tin", "station_canto": "沙田", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/sht.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/sht.pdf"},
    {"station_eng": "Fo Tan", "station_canto": "火炭", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/fot.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/fot.pdf"},
    {"station_eng": "Racecourse", "station_canto": "馬場", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/rac.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/rac.pdf"},
    {"station_eng": "University", "station_canto": "大學", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/uni.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/uni.pdf"},
    {"station_eng": "Tai Po Market", "station_canto": "大埔墟", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tap.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tap.pdf"},
    {"station_eng": "Tai Wo", "station_canto": "太和", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/taw.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/taw.pdf"},
    {"station_eng": "Fanling", "station_canto": "粉嶺", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/fan.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/fan.pdf"},
    {"station_eng": "Sheung Shui", "station_canto": "上水", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/shs.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/shs.pdf"},
    {"station_eng": "Lo Wu", "station_canto": "羅湖", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/low.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/low.pdf"},
    {"station_eng": "Lok Ma Chau", "station_canto": "落馬洲", "line": "East Rail",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/lmc.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/lmc.pdf"}
]

tuen_ma_line_stations = [
    {"station_eng": "Tuen Mun", "station_canto": "屯門", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tum.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tum.pdf"},
    {"station_eng": "Siu Hong", "station_canto": "兆康", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/sih.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/sih.pdf"},
    {"station_eng": "Tin Shui Wai", "station_canto": "天水圍", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tsw.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tsw.pdf"},
    {"station_eng": "Long Ping", "station_canto": "朗屏", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/lop.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/lop.pdf"},
    {"station_eng": "Yuen Long", "station_canto": "元朗", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/yul.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/yul.pdf"},
    {"station_eng": "Kam Sheung Road", "station_canto": "錦上路", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/ksr.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/ksr.pdf"},
    {"station_eng": "Tsuen Wan West", "station_canto": "荃灣西", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tww.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tww.pdf"},
    {"station_eng": "Mei Foo", "station_canto": "美孚", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/mef.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/mef.pdf"},
    {"station_eng": "Nam Cheong", "station_canto": "南昌", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/nac.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/nac.pdf"},
    {"station_eng": "Austin", "station_canto": "柯士甸", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/aus.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/aus.pdf"},
    {"station_eng": "East Tsim Sha Tsui", "station_canto": "尖東", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/ets.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/ets.pdf"},
    {"station_eng": "Hung Hom", "station_canto": "紅磡", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/huh.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/huh.pdf"},
    {"station_eng": "Ho Man Tin", "station_canto": "何文田", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/hom.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/hom.pdf"},
    {"station_eng": "To Kwa Wan", "station_canto": "土瓜灣", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tkw.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tkw.pdf"},
    {"station_eng": "Sung Wong Toi", "station_canto": "宋皇臺", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/suw.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/suw.pdf"},
    {"station_eng": "Kai Tak", "station_canto": "啟德", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/kat.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/kat.pdf"},
    {"station_eng": "Diamond Hill", "station_canto": "鑽石山", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/dih.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/dih.pdf"},
    {"station_eng": "Hin Keng", "station_canto": "顯徑", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/hik.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/hik.pdf"},
    {"station_eng": "Tai Wai", "station_canto": "大圍", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/taw.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/taw.pdf"},
    {"station_eng": "Che Kung Temple", "station_canto": "車公廟", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/ckt.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/ckt.pdf"},
    {"station_eng": "Sha Tin Wai", "station_canto": "沙田圍", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/stw.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/stw.pdf"},
    {"station_eng": "City One", "station_canto": "第一城", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/cio.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/cio.pdf"},
    {"station_eng": "Shek Mun", "station_canto": "石門", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/shm.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/shm.pdf"},
    {"station_eng": "Tai Shui Hang", "station_canto": "大水坑", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tsh.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tsh.pdf"},
    {"station_eng": "Heng On", "station_canto": "恆安", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/heo.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/heo.pdf"},
    {"station_eng": "Ma On Shan", "station_canto": "馬鞍山", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/mos.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/mos.pdf"},
    {"station_eng": "Wu Kai Sha", "station_canto": "烏溪沙", "line": "Tuen Ma",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/wks.pdf", 
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/wks.pdf"}
]

airport_express_stations = [
    {"station_eng": "Hong Kong", "station_canto": "香港", "line": "Airport Express",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/hok.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/hok.pdf"},
    {"station_eng": "Kowloon", "station_canto": "九龍", "line": "Airport Express",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/kow.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/kow.pdf"},
    {"station_eng": "Tsing Yi", "station_canto": "青衣", "line": "Airport Express",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/tsy.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/tsy.pdf"},
    {"station_eng": "Airport", "station_canto": "機場", "line": "Airport Express",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/air.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/air.pdf"},
    {"station_eng": "AsiaWorld-Expo", "station_canto": "博覽館", "line": "Airport Express",
     "location_map_url": "https://www.mtr.com.hk/archive/ch/services/maps/awe.pdf",
     "station_map_url": "https://www.mtr.com.hk/archive/ch/services/layouts/awe.pdf"}
]

# Combining all the Lists of all stations
stations = [*kwun_tong_stations + tsuen_wan_stations + island_line_stations + south_island_line_stations +
             tseung_kwan_o_line_stations + tung_chung_line_stations + disneyland_resort_line_stations +
             east_rail_line_stations + tuen_ma_line_stations + airport_express_stations]
             
print(len(stations))

#print(stations[0:4])

def get_coordinates(station_name):
    """ Function to fetch coordinates of the station name by using Google Maps Geocoding API """
    url = f"https://maps.googleapis.com/maps/api/geocode/json?address={station_name},HongKong&key={API_KEY}"
    response = requests.get(url)
    data = response.json()
    if data['status'] == 'OK':
        location = data['results'][0]['geometry']['location']
        return location['lat'], location['lng']
    else:
        return None, None


# List to hold the station data with coordinates
station_data = []

# Get coordinates for each station and safes it in data structure
for station in tqdm(stations):
    # using station name in english + MTR for more accurate results
    lat, lng = get_coordinates(station["station_eng"]+ " MTR")
    station_data.append({
        "station_eng": station["station_eng"],
        "station_canto": station["station_canto"],
        "line": station["line"],
        "lat": lat,
        "long": lng,
        "location_map_url": station["location_map_url"],
        "station_map_url": station["station_map_url"]
    })

station_df = pd.DataFrame(station_data)
print(station_df)

# export result to csv file
station_df.to_csv("stations_with_coords_and_maps.csv", index=False)
